### ISSUE TITLE
random generator is taken from gym.seeding

### ISSUE THREAD

**Issue by tinubuerki** [flatland-association/flatland-rl#25]
### Objectives

malfunction_generators, rail_generators and timetable_generators call the method randint() from an object named np_random which is created in RailEnv (by calling self._seed that itself calls gym.seeding).

Depending on the configuration used (e.g. the version of gym/gymnasium) a warning or error is thrown when calling randint():
`AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'`

### Out of scope : Remove the dependencies to Gym
https://github.com/flatland-association/flatland-rl/issues/26

### Todos
Possible solution:
- [ ] create np_random in RailEnv directly from numpy.random.Generator
- [ ] use calls np_random.integers() instead of np_random.randint() in malfunction_generators, rail_generators and timetable_generators

### Minimal testing requirements
- [ ] …

**Comment by fnberta** [comment]
Fixed in https://github.com/flatland-association/flatland-rl/pull/56.
